<a href="https://colab.research.google.com/github/Saif-Saket/100-pandas-puzzles/blob/master/_downloads/3dbbd6931d76adb0dc37d4e88b328852/tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# For tips on running notebooks in Google Colab, see
# https://docs.pytorch.org/tutorials/beginner/colab
%matplotlib inline

Tensors
=======

Tensors are a specialized data structure that are very similar to arrays
and matrices. In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model's parameters.

Tensors are similar to NumPy's ndarrays, except that tensors can run on
GPUs or other specialized hardware to accelerate computing. If you're
familiar with ndarrays, you'll be right at home with the Tensor API. If
not, follow along in this quick API walkthrough.


In [2]:
import torch
import numpy as np

Tensor Initialization
=====================

Tensors can be initialized in various ways. Take a look at the following
examples:

**Directly from data**

Tensors can be created directly from data. The data type is
automatically inferred.


In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see
`bridge-to-np-label`{.interpreted-text role="ref"}).


In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument
tensor, unless explicitly overridden.


In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1710, 0.7520],
        [0.9469, 0.2179]]) 



**With random or constant values:**

`shape` is a tuple of tensor dimensions. In the functions below, it
determines the dimensionality of the output tensor.


In [6]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1475, 0.2342, 0.7585],
        [0.5103, 0.1463, 0.2656]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


------------------------------------------------------------------------


Tensor Attributes
=================

Tensor attributes describe their shape, datatype, and the device on
which they are stored.


In [7]:
"""
# the attributes of the tesors are (shape, ndim, dtype, device):
  - ndim: the num of dimention of the tensor (0 "Scalar", 1 "vector", 2 "Matrix", 3 "tensor")
  - shape: we explained it before, it return value like: torch.Size([3, 4]) which is a <class 'torch.Size'>.
    # we can access it by index [0] => first value [1]...
  - dtype: return the datatype of the tensor (which is a tensor data) ex: torch.float32 (tensor with float32 data).
  - device: the device of that the tensor are stored in (CPU, GPU, TPU).
"""
tensor = torch.rand(3, 4)

print(f"the tensor: \n{tensor}\n")
print(f"Shape of tensor: {tensor.shape}")
print(f"ndim of tensor: {tensor.ndim}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
print(type(tensor.shape))

the tensor: 
tensor([[0.5198, 0.1791, 0.1042, 0.6124],
        [0.3983, 0.9729, 0.9895, 0.8263],
        [0.2390, 0.4012, 0.3419, 0.7188]])

Shape of tensor: torch.Size([3, 4])
ndim of tensor: 2
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
<class 'torch.Size'>


------------------------------------------------------------------------


Tensor Operations
=================

Over 100 tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random sampling, and more are
comprehensively described
[here](https://pytorch.org/docs/stable/torch.html).

Each of them can be run on the GPU (at typically higher speeds than on a
CPU). If you're using Colab, allocate a GPU by going to Edit \> Notebook
Settings.


In [8]:
"""
# we need to move the tensor to GPU to apply Operations faster.
# first by the "torch.cuda" class we use the ".is_available()" method to check if the cuda are available.
# if it is available we move the tensor by the "tensor_var.to()" and spesify the 'cuda' => tensor.to('cuda').
# we then check the device attribute for that tensor
"""
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


Try out some of the operations from the list. If you\'re familiar with
the NumPy API, you\'ll find the Tensor API a breeze to use.


**Standard numpy-like indexing and slicing:**


In [9]:
tensor = torch.ones(4, 4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors** You can use `torch.cat` to concatenate a sequence of
tensors along a given dimension. See also
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining op that is subtly different from `torch.cat`.


In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**Tensors datatypes**

In [12]:
"""
# by default when we create a tenosr by (torch.tensor, .rand, .zeros, .ones, .rand_like...) the tensor Datatype is the "torch.float32" but we can change it.
# the tensors Datatype is very importent because it takes spaces in the memory and any Operation is faster on the small datatypes ex: float16 (faster than) float32,
  and it's one of the 3 big errors to manipulate in the Pytorch:
  1. Tensors not right datatypes => can't apply Operations between them.
  2. Tensors not right shape.           [ we will learn later how ]
  3. Tensors not in the right device.   [ to manipulat that isues ]
"""

# the default tensor datatype is "torch.float32":
tensor = torch.tensor([])

print(f"Tensor datatype: {tensor.dtype}") # it is by default is "torch.float32"

Tensor datatype: torch.float32


In [13]:
"""
# all the other ways to create a tenosrs the default datatype is "torch.float32"
"""
random_tensor = torch.rand(size = (2, 3))
zeros_tensor = torch.zeros(size = (2, 3))
ones_tensor = torch.ones(size = (2, 3))

# also the tensor_like methods (rand_like, zeros_like, ones_like):
rand_like_tenosr = torch.rand_like(zeros_tensor)

print(f"ranodm Tensor datatype: {random_tensor.dtype}")
print(f"zeros Tensor datatype: {zeros_tensor.dtype}")
print(f"ones Tensor datatype: {ones_tensor.dtype}")
print(f"like Tensor datatype: {rand_like_tenosr.dtype}")

ranodm Tensor datatype: torch.float32
zeros Tensor datatype: torch.float32
ones Tensor datatype: torch.float32
like Tensor datatype: torch.float32


In [14]:
"""
# the default DataType of the tensor is:
  - for integers inputs => torch.int64
  - for float inputs => torch.float32
"""

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([1., 2., 3.])

print(f"tensor1 Datatype: {tensor1.dtype}")
print(f"tensor2 Datatype: {tensor2.dtype}")

tensor1 Datatype: torch.int64
tensor2 Datatype: torch.float32


In [15]:
"""
# to change the Datatype we use ".type(Type)" or ".to(Type)":
"""
tensor1 = tensor1.type(torch.int8)             #.to(torch.int8)
tensor2 = tensor2.type(torch.float16)          #.to(torch.float16)

# the datatypes changed (int64 => int8 float32 => float16):
print(f"tensor1 Datatype: {tensor1.dtype}")
print(f"tensor2 Datatype: {tensor2.dtype}")

tensor1 Datatype: torch.int8
tensor2 Datatype: torch.float16


In [16]:
"""
# the bits in datatypes is important to (save ununsed memory + apply faster operations).
# for float: 3.123456789
  - float 16 => 16 bits => stores (3 - 4) decimal after the point ex: (3.123)
  - float 32 => 32 bits => stores (6 - 7) decimal ex: (3.1234567)
  - float 64 => 64 bits => stores (10) decimals ex: (3.123456789)
# for int:
  - int 8 => 8 bits => number between (-128 _ -127)
  - int 16 => 16 bits => number between (-32k _ 32k)
  - int 32 => 32 bits => number between (-2100M  _ 2100M)
  - int 64 => 64 bits => number between (very large number)
  # the different between signed and unsigned is (signed save the sing (+ / -) and unsigned don't save it (all +))
"""

"\n# the bits in datatypes is important to (save ununsed memory + apply faster operations).\n# for float: 3.123456789\n  - float 16 => 16 bits => stores (3 - 4) decimal after the point ex: (3.123)\n  - float 32 => 32 bits => stores (6 - 7) decimal ex: (3.1234567)\n  - float 64 => 64 bits => stores (10) decimals ex: (3.123456789)\n# for int:\n  - int 8 => 8 bits => number between (-128 _ -127)\n  - int 16 => 16 bits => number between (-32k _ 32k)\n  - int 32 => 32 bits => number between (-2100M  _ 2100M)\n  - int 64 => 64 bits => number between (very large number)\n  # the different between signed and unsigned is (signed save the sing (+ / -) and unsigned don't save it (all +))\n"

In [17]:
"""
### Operations between different types.
  - between 1. (different floats) 2. (different ints) ex: torch.float16 * torch.float32 (it converted to the bigger type) torch.float32
  - between integer tensor and float tensor => the result is torch.float tensor.
  - between numeric number and Boolean => ERROR!!!
"""
# Examples:

# different Datatypes with the same (Datatype Family):
float_32_tensor = torch.tensor([1., 2., 3.])
float_16_tensor = torch.tensor([1., 2., 3.], dtype = torch.float16)

print("# different Datatypes with the same (Datatype Family):\n")
print(f"float32 * float16:\n{float_32_tensor * float_16_tensor}")
print(f"Type: {(float_32_tensor * float_16_tensor).dtype}")

# integer * float:
int_tensor = torch.tensor([1., 2., 3.], dtype= torch.int8)
float_tensor = torch.tensor([1., 2., 3.], dtype = torch.float16)
print("\n# integer * float:\n")
print(f"integer * float:\n{int_tensor * float_tensor}")
print(f"Type: {(int_tensor * float_tensor).dtype}")

# different Datatypes with the same (Datatype Family):

float32 * float16:
tensor([1., 4., 9.])
Type: torch.float32

# integer * float:

integer * float:
tensor([1., 4., 9.], dtype=torch.float16)
Type: torch.float16


In [18]:
"""
# change the data type of the tensor by "dtype" parameter in the torch.tensor"
"""
tensor = torch.tensor([2., 3.], dtype = torch.float16) # also to int8, 16, 32...
tensor, tensor.dtype

(tensor([2., 3.], dtype=torch.float16), torch.float16)

In [19]:
# change type of tensor in torch.rand (from torch.float32 => torch.float16)
tensor = torch.rand(2, 3, dtype = torch.float16)
tensor, tensor.dtype

(tensor([[0.1431, 0.1504, 0.0464],
         [0.0483, 0.3589, 0.0010]], dtype=torch.float16),
 torch.float16)

**Tensors (Mathmatical Operation)**

In [20]:
"""
# we can apply a Mathmatical Operations on Tensors:
  - addition, subtraction
  - multiplication (element wise multiplication), devision
  - Matrix multiplication (Dot Product)
"""
MATRIX = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

# MATRIX +, -, *, / Scalar => apply the value element wise
MATRIX - 1

tensor([[0, 1, 2],
        [3, 4, 5]])

In [21]:
"""
# MATRIX (+, -, *, /) MATRIX (Normal operations) => element wise ex: element in M1 - element in M2
# they should be THE SAME size.
"""

MATRIX1 = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

MATRIX2 = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

print(f"Matries Sum: \n{MATRIX1 + MATRIX2}\n")
print(f"\nMatries Multiply: \n{MATRIX1 * MATRIX2}\n")

Matries Sum: 
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


Matries Multiply: 
tensor([[ 1,  4,  9],
        [16, 25, 36]])



In [22]:
"""
# the most operation in PyTorch is the "Dot Product" as we learn it have 2 Rules:
  1. The inner values in shape must be the same thing:
     (2 * 3) . (2 * 3) => Error!! (3 not eqal 2)
     (4 * 2) . (2 * 8) => Yes (2 == 2)
  2. The result is the Outer values in shape (a * b) . (b * c) => result (a * c)
     (4 * 2) . (2 * 2) => result (4 * 2)

"""
# create Matries:
M1 = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

M2 = torch.tensor([[1, 2],
                   [3, 4],
                   [5, 6]])

print(f"M1:\n{M1}\n{M1.shape}\n\nM2:\n{M2}\n{M2.shape}")

M1:
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])

M2:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


In [23]:
"""
# because the inner values are the same 3 ==3 so M1 torch.Size([2, 3]) M2 torch.Size([3, 2]), so we can apply Dot Product and the result are Outers[2 * 2].
# to apply the "Dot Product" in Pytorch we can use:
  - "@" symbol => M1 @ M2
  - .matmul(Matrix multiplication) method => torch.matmul(M1, M2)
  # there is a short-cut method for the matmul() which is ".mm()".
"""
# Matrix detales:
print(f"M1:\n{M1}\n{M1.shape}")
print(f"\nM2:\n{M2}\n{M2.shape}\n")

# Matrix Multiplication:
torch.matmul(M1, M2)

M1:
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])

M2:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])



tensor([[22, 28],
        [49, 64]])

In [24]:
"""
# the most common error we will see is when we try to apply "Dot Product" in Uncorrect shape.
# the error is "mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)"
"""
# Error Matrix shape:
M3 = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])
print("could we apply Dot Product for:")
print(f"M1:\n{M1}\n{M1.shape}")
print(f"\nM3:\n{M3}\n{M3.shape}\n")

could we apply Dot Product for:
M1:
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])

M3:
tensor([[ 7,  8,  9],
        [10, 11, 12]])
torch.Size([2, 3])



In [25]:
# Shape error in multiplication:
torch.matmul(M1, M3)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

**Matrix Transpos**

In [26]:
# Matrix to use:
print(f"M1:\n{M1}\n{M1.shape}")
print(f"\nM2:\n{M2}\n{M2.shape}\n")
print(f"\nM3:\n{M3}\n{M3.shape}\n")


M1:
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])

M2:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


M3:
tensor([[ 7,  8,  9],
        [10, 11, 12]])
torch.Size([2, 3])



In [27]:
"""
# Transpose we use when we need to rotat the Matrix to apply the "Dot Product".
# the Transpose switch the shape (2 * 3) => (3 * 2).
# for each column rotate it iverce of the clock (🔄) to be a row.
# to Transpose a Matrix we use ".T" on the matrix => matrix.T
"""
print(f"M3:\n{M3}\n{M3.shape}\n")
print(f"\nM3:\n{M3.T}\n{M3.T.shape}\n")

M3:
tensor([[ 7,  8,  9],
        [10, 11, 12]])
torch.Size([2, 3])


M3:
tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
torch.Size([3, 2])



In [28]:
# we can Multiply the M1 and transpose of M3:


In [29]:
print(f"\nM1:\n{M1}\n{M1.shape}\n")
print(f"\nM3:\n{M3.T}\n{M3.T.shape}\n")

print(f"M1 . M3.T:\n{torch.matmul(M1, M3.T)}\n{torch.matmul(M1, M3.T).shape}")


M1:
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


M3:
tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
torch.Size([3, 2])

M1 . M3.T:
tensor([[ 50,  68],
        [122, 167]])
torch.Size([2, 2])


**Tensor aggregation (min, max, sum, mean) + (minarg, maxarg)**

In [30]:
"""
# to find the aggregation we can use one of these syntacs:
  - torch.agg(Tensor) => torch.min(M1)
  - Tensor.agg() => M1.min()
"""
M = M1.type(torch.float32)
# we will use this tensor
print(f"\nM1:\n{M}")


M1:
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [31]:
# min:
print(f"min:\n{torch.min(M), M.min()}\n")

# max:
print(f"max:\n{torch.max(M), M.max()}")

min:
(tensor(1.), tensor(1.))

max:
(tensor(6.), tensor(6.))


In [32]:
# to find the "sum" use:
print(f"max:\n{torch.sum(M), M.sum()}")

max:
(tensor(21.), tensor(21.))


In [35]:
"""
# the mean function only take input of (float or complex) in doesn't take the integer or long.
"""
# M.type(torch.int32).mean() # Error!! long datatype

# only with float or complex:
M.dtype, torch.mean(M), M.mean()

(torch.float32, tensor(3.5000), tensor(3.5000))

In [40]:
"""
# some time we don't need to find the (min) or (max) we need to find the index of them, so we use the "argmin" and "argmax".
# we need the "argmin" and "argmax" in the Softmax function.
"""
print(M)

# argmin:
torch.argmin(M), M.argmin() # index (0) the minimum number [1]

tensor([[1., 2., 3.],
        [4., 5., 6.]])


(tensor(0), tensor(0))

In [41]:
#argmax:
torch.argmax(M), M.argmax() # index (5) the maximum number [6]

(tensor(5), tensor(5))

**Reshaping, stacking, squeezing, and unsqueezing Tensors**

In [ ]:
"""
# these are importent topics in the Tesors manipulation.
"""

**Multiplying tensors**


In [ ]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

This computes the matrix multiplication between two tensors


In [ ]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

**In-place operations** Operations that have a `_` suffix are in-place.
For example: `x.copy_(y)`, `x.t_()`, will change `x`.


In [ ]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>

</div>



------------------------------------------------------------------------


Bridge with NumPy {#bridge-to-np-label}
=================

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change the other.


Tensor to NumPy array
=====================


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

A change in the tensor reflects in the NumPy array.


In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

NumPy array to Tensor
=====================


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.


In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")