In [1]:
# For tips on running notebooks in Google Colab, see
# https://docs.pytorch.org/tutorials/beginner/colab
%matplotlib inline

Tensors
=======

Tensors are a specialized data structure that are very similar to arrays
and matrices. In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model's parameters.

Tensors are similar to NumPy's ndarrays, except that tensors can run on
GPUs or other specialized hardware to accelerate computing. If you're
familiar with ndarrays, you'll be right at home with the Tensor API. If
not, follow along in this quick API walkthrough.


In [2]:
import torch
import numpy as np

Tensor Initialization
=====================

Tensors can be initialized in various ways. Take a look at the following
examples:

**1. Directly from data**

Tensors can be created directly from data. The data type is
automatically inferred.


In [7]:
data = [[1, 2],
        [3, 4]]
x_data = torch.tensor(data)

In [11]:
x_data

tensor([[1, 2],
        [3, 4]])

**From a 2. NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see
`bridge-to-np-label`{.interpreted-text role="ref"}).


In [15]:
"""
# we can convert data from np.array to torch.Tensor and vise versa.
# to convert from np.array to tensor we use the "torch.from_numpy()" function and send the np.array in the function.
"""
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument
tensor, unless explicitly overridden.


In [18]:
# remember "x_data" is a torch.Tensor:
print(f"""
x_data:\n {x_data}
ndim: {x_data.ndim}
shape: {x_data.shape}""")


x_data:
 tensor([[1, 2],
        [3, 4]])
ndim: 2
shape: torch.Size([2, 2])


In [41]:
"""
# create a tensor like other tensors by (.ones_like, rand_like).
# both the ".ones_like()" and "rand_like()" by default create a Tensor with same proparities (Shape, datatype).
# the ".ones_like()" create a tensor with the same proparities with all elements are ones.
# the ".rand_like()" create a tensor with the same proparities with all elements are random float numbers ex:(0.8346).
# we can Overrides the type by use the "dtype".
# because the tensors_like methods return a tensors with the same 'dtype' we must convert the type if the tensor_like method generate a different type data, ex:
  the "rand_like()" generate a (random float data) so we must change the dtype to torch.float.
# the ".randn_like()" create a tensor with the same proparities but with random float (Positive and Negative) numbers.
"""
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0573, 0.6347],
        [0.2561, 0.3903]]) 



In [45]:
"""
# we have the same idea for ()
"""
x_zeros = torch.zeros_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_zeros} \n")

x_randn = torch.randn_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_randn} \n")

Ones Tensor: 
 tensor([[0, 0],
        [0, 0]]) 

Random Tensor: 
 tensor([[ 0.5305, -1.3512],
        [-0.9292, -0.9936]]) 



**With random or constant values:**

`shape` is a tuple of tensor dimensions. In the functions below, it
determines the dimensionality of the output tensor.


In [55]:
"""
# we can generate a tensors with a different shapes with (.rand(), .zeros(), .ones()).
# we should spesify the shape by a "tuple" or "list".

- zeros: a tensor with zeros
- ones: a tensor with ones
- rand: a tensor with random numbers between 0 and 1 in this range [0, 1).
# the "shape" we will explain it more but in breafe:
  - shape 0 numbers => a 0 dimention tensor (one number(Scalar)). shape = ()
  - shape 1 number => a 1 dimention tensor (vector) with the number of elements. shape = (3) 3 elements
  - shape 2 numbers => a 2 dimention tensor (Matrix) with (num of rows, num of columns). shape = (2, 3) matrix 2 rows * 3 columns
  - shape 3 numbers => a 3 dimention tensor (3D-tensor) with (num of faces, num of rows, num of columns)
    shape = (5, 2, 3) 5 faces(Matrix) each matrix is 2 rows * 3 columns.
"""

shape = (3, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9642, 0.9773, 0.8965],
        [0.0241, 0.4204, 0.5455],
        [0.0530, 0.6381, 0.2457]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


------------------------------------------------------------------------


Tensor Attributes
=================

Tensor attributes describe their shape, datatype, and the device on
which they are stored.


In [59]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


------------------------------------------------------------------------


Tensor Operations
=================

Over 100 tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random sampling, and more are
comprehensively described
[here](https://pytorch.org/docs/stable/torch.html).

Each of them can be run on the GPU (at typically higher speeds than on a
CPU). If you're using Colab, allocate a GPU by going to Edit \> Notebook
Settings.


In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Try out some of the operations from the list. If you\'re familiar with
the NumPy API, you\'ll find the Tensor API a breeze to use.


**Standard numpy-like indexing and slicing:**


In [ ]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

**Joining tensors** You can use `torch.cat` to concatenate a sequence of
tensors along a given dimension. See also
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining op that is subtly different from `torch.cat`.


In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

**Multiplying tensors**


In [ ]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

This computes the matrix multiplication between two tensors


In [ ]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

**In-place operations** Operations that have a `_` suffix are in-place.
For example: `x.copy_(y)`, `x.t_()`, will change `x`.


In [ ]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>

</div>



------------------------------------------------------------------------


Bridge with NumPy {#bridge-to-np-label}
=================

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change the other.


Tensor to NumPy array
=====================


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

A change in the tensor reflects in the NumPy array.


In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

NumPy array to Tensor
=====================


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.


In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")